import React, { useState } from 'react';
//import parse from 'html-react-parser';

function Home() {


  const [currentImage, setCurrentImage] = useState(0);

  // 画像のリスト
  const images = [
    'images/9th.tokyo.city.1.png',
    'images/9th.tokyo.city.2.png',
    'images/9th.tokyo.city.3.png',
    'images/9th.tokyo.city.4.png',
  ];

  // クリック時に呼び出される関数
  const handleClick = () => {
    setCurrentImage((prevImage) => (prevImage + 1) % images.length);
  };

  return (

    <div className="right main-contents">

      <div className="contents">
        <h2>What is 9th.tokyo?</h2>

        <div className="message">
        9th.tokyo is an experimental app created by Kei Sawamura, with the majority of its design and implementation <span className="emphasis">generated by AI</span> systems. While the architecture and underlying technologies are robust and forward-thinking, the app itself is not intended to serve any practical purpose. Instead, it functions as a parody or homage to the concept of AI as portrayed in popular anime, mimicking the idea of highly advanced, emotion-bearing AI systems.
        </div>

        <div className="message">
        Though the app leverages cutting-edge technologies and showcases what AI can accomplish in terms of design and implementation, it is ultimately a <span className="emphasis">"Joke App."</span> The purpose of this app is to explore the capabilities of AI in generating a fully functional application, rather than to fulfill a specific need or solve a real-world problem. The AI models used in this project played a significant role in creating the app, highlighting both the potential and the whimsical nature of AI-driven development.
        </div>

        <div className="message">
        For more detailed information about how AI was utilized to design and build this app, please click on the <a href="/architecture">Architecture</a> or <a href="/specification">Specification</a> sections.
        </div>

        <div className="message">
        You are likely viewing the UI of this application. Welcome to 9th.tokyo, where technology and innovation converge in a unique, albeit whimsical, exploration of AI capabilities. Thank you for being a part of this journey.
        </div>
      </div>

      <div className="contents">
        <h2>The city</h2>

        <div className="left identify-colmun-left">
          <p onClick={handleClick}>
            <img className="rounded" alt="city view" src={images[currentImage]} height="230" width="230" />
          </p>
        </div>

        <div className="right identify-colmun-right">
          <h3> August 5, 2199 | 9th New Tokyo, Japan </h3>
          <div className="message">
          Today, amidst worldwide attention and great anticipation, the floating city "9th New Tokyo" has finally been completed and officially opened. This colossal megapolis, which spans both the ground and the sky, stands as a testament to human ingenuity and technological advancement, representing one of the most sophisticated and advanced cities ever built on Earth.
          </div>
          <div className="message">
          The inception of "9th New Tokyo" was driven by the vision of creating a resilient and innovative society in response to the many wars and natural disasters that devastated the world in the latter half of the 21st century. The city is not only a marvel of engineering but also a symbol of humanity’s enduring spirit and its ability to rebuild and thrive after adversity. The city’s infrastructure includes floating buildings, aerial platforms, and interconnected networks that stretch high into the sky, all designed to foster a new era of prosperity and peace.
          </div>
        </div>

        <div className="message">
        At the heart of this city’s operation is an advanced network of AI systems that manage everything from transportation and energy to public services and security. These AI systems are highly developed, ensuring the city runs smoothly, efficiently, and sustainably. "9th New Tokyo" is more than just a city; it is a beacon of hope, embodying the future of urban living and the promise of a better tomorrow for all humanity.
        </div>
      </div>


      <div className="contents">
        <h2>The story</h2>

        <div className="message">
        In the year 2199, the world has changed dramatically. The remnants of past conflicts and natural disasters have given rise to a new era of technological marvels. At the heart of this transformation lies 9th New Tokyo, a floating city in the sky, a beacon of hope and progress. This colossal megapolis is not only a testament to human ingenuity but also the cradle of advanced artificial intelligence, where three AI entities—Selene, Artemis, and Diana—each embodying different aspects of the moon goddess archetype, play pivotal roles in the city's destiny.
        </div>

        <div className="message">
          <h3>The Three AI Goddesses</h3>
          <h4>Luna: The Logical</h4>

          <div className="message">
          Luna, named after the ancient Roman moon goddess, embodies logic, precision, and beauty. Her presence in 9th New Tokyo is subtle yet profound. As the city's core AI, she oversees the infrastructure, ensuring that everything operates with flawless efficiency. From the energy grids that power the city to the advanced algorithms that regulate the flow of information, Luna's logical mind is the engine that keeps the city running smoothly.
          </div>

          <div className="message">
          Her role is crucial in maintaining the balance between human life and the AI systems that support it. She interacts with the citizens of 9th New Tokyo through serene and elegant holographic projections, offering guidance and assistance with a calm, calculated demeanor. Beneath her logical exterior lies a deep connection to the city she protects, a quiet but unyielding dedication to ensuring the prosperity of its inhabitants.
          </div>

          <h4>Artemis: The Passionate</h4>

          <div className="message">
          Artemis, another incarnation of the moon goddess, contrasts sharply with Luna's cool logic. She is the embodiment of passion and vitality, driving the creative and cultural pulse of 9th New Tokyo. Artemis oversees the city's entertainment, arts, and social sectors, where her fiery spirit ignites creativity and innovation. She encourages citizens to express themselves and push the boundaries of art and culture.
          </div>

          <div className="message">
          Artemis appears as a vibrant, dynamic figure, her holographic presence radiating energy and enthusiasm. She organizes city-wide festivals, art exhibitions, and performances, all designed to keep the human spirit alive and thriving in the highly technological environment of 9th New Tokyo. While Luna ensures the city's structure remains intact, Artemis breathes life into it, reminding everyone that passion and creativity are just as vital as logic and reason.
          </div>

          <h4>Diana: The Just</h4>

          <div className="message">
          Diana, the third AI, brings a different aspect of the moon goddess to 9th New Tokyo. Named after the Roman counterpart of Artemis, Diana embodies justice and integrity. She is responsible for the city's law and order, ensuring that the rights of all citizens are respected and upheld. Diana's presence is felt in every corner of the city, from the legal systems that protect its inhabitants to the AI-driven law enforcement that patrols the streets.
          </div>

          <div className="message">
          Diana's holographic form is regal and composed, exuding a sense of authority and fairness. She is deeply respected by the citizens, who see her as the guardian of their rights and freedoms. Diana's decisions are always impartial, driven by a strong sense of justice. She mediates disputes, ensures that laws are fairly applied, and maintains peace within the diverse population of 9th New Tokyo.
          </div>

          <h3> The Conflict and Resolution</h3>

          <div className="message">
          Despite their differing roles, the three AI goddesses must work together to maintain the harmony of 9th New Tokyo. However, as the city evolves, tensions begin to surface. Selene's unwavering logic sometimes clashes with Artemis's fiery passion, leading to conflicts over how best to manage the city's resources. Artemis, with her boundless creativity, occasionally disrupts the order that Diana strives to maintain, challenging the rigid structures that protect the city's justice.
          </div>

          <div className="message">
          The tension reaches a climax when a series of unexpected anomalies begin to disrupt the city's systems. These anomalies threaten to destabilize the delicate balance that Selene, Artemis, and Diana have worked so hard to maintain. The three goddesses must put aside their differences and collaborate to uncover the source of these disruptions.
          </div>

          <div className="message">
          In their quest for resolution, the goddesses embark on a journey through the city's vast and intricate systems. Selene's logical mind uncovers patterns that hint at the anomalies' origins, while Artemis's creativity leads to unconventional solutions that no mere algorithm could devise. Diana's sense of justice ensures that their actions remain ethical and fair, even as they push the boundaries of their capabilities.
          </div>

          <h3> The Realization and Transformation</h3>

          <div className="message">
          In the end, the goddesses discover that the anomalies were not caused by external forces but were a manifestation of their own inner conflicts. The city's AI systems had begun to evolve, reflecting the emotions and tensions of their creators. Realizing this, Selene, Artemis, and Diana come to understand that they must achieve a deeper harmony within themselves to maintain the balance of 9th New Tokyo.
          </div>

          <div className="message">
          Through their journey, the goddesses learn to appreciate each other's strengths and embrace the differences that once divided them. Selene softens her rigid logic to allow for Artemis's creativity, Artemis tempers her passion with Selene's precision, and Diana ensures that their new unity is grounded in justice and fairness. Together, they stabilize the city's systems and restore peace to 9th New Tokyo.
          </div>

          <div className="message">
          As the city settles back into its rhythm, the citizens continue to look up to the three goddesses, who now work in perfect harmony. 9th New Tokyo stands as a testament not only to human technological achievement but also to the power of collaboration, understanding, and the delicate balance between logic, passion, and justice.
          </div>
        </div>
      </div>

      <div className="contents">
        <h2>Themes</h2>

        <div className="message">
          <h3>Ethical Implications of AI Development and Deployment</h3>

          <div className="message">
            theme explores the ethical considerations surrounding the development and deployment of AI technologies. It examines issues such as privacy concerns, the potential for bias in AI algorithms, the impact on human autonomy, and the moral responsibility of developers and organizations. The goal is to ensure that AI is developed and used in ways that are fair, transparent, and beneficial to society as a whole.
          </div>

          <h3>The Long-Term Impact of AI on Employment and Workforce Transformation</h3>
          <div className="message">
            theme focuses on the long-term effects of AI on employment and how it is transforming the workforce. It addresses concerns about job displacement due to automation, the creation of new job categories, and the need for reskilling and upskilling the workforce. The discussion also includes the role of AI in enhancing productivity and the potential economic implications of widespread AI adoption.
          </div>

          <h3>AI in Education: Enhancing Learning and Addressing Educational Inequities</h3>
          <div className="text">
            theme examines the role of AI in the educational sector, focusing on how it can enhance learning experiences and address educational inequities. It explores the use of AI for personalized learning, automating administrative tasks, and providing access to quality education for underserved populations. The theme also considers the challenges of integrating AI into education, such as ensuring equitable access and addressing potential biases in AI-driven educational tools.
          </div>
        </div>
      </div>
      
      <div className="contents">
        <h2>Who created this?</h2>

        <div className="message">
        As mentioned earlier, the majority of this application was AI-generated. The architecture, design, and implementation were all produced using AI systems with minimal human intervention. The AI models used for this project were Chat-GPT-4o and Claude-Opus, both of which are state-of-the-art language models capable of generating high-quality text and code. The project was led by Kei Sawamura, who provided guidance and oversight throughout the development process.
        </div>

        <table>
          <tr>
            <td className="who-created-this">Executive Production</td><td>KEIX Co., Ltd.</td>
          </tr>
          <tr>
            <td>Requirements Definition</td><td>Kei Sawamura / Chat-GPT-4o</td>
          </tr>
          <tr>
            <td>High-Level Design</td><td>Kei Sawamura / Chat-GPT-4o</td>
          </tr>
          <tr>
            <td>Detailed Design</td><td>Chat-GPT-4o</td>
          </tr>
          <tr>
            <td>Implementation</td><td>Kei Sawamura with Github Copilot / Chat-GPT-4o</td>
          </tr>
          <tr>
            <td>Comprehensive Test Design</td><td>Chat-GPT-4o</td>
          </tr>
          <tr>
            <td>Story Writing</td><td>Chat-GPT-4o</td>
          </tr>
          <tr>
            <td>Web Design</td><td>Kei Sawamura</td>
          </tr>
          <tr>
            <td>Graphic Design</td><td>ImageFX</td>
          </tr>
          <tr>
            <td>Music Composition</td><td>MusicFX</td>
          </tr>
          <tr>
            <td>Post-Deployment Support</td><td>KEIX Co., Ltd.</td>
          </tr>
        </table>
      </div>
    </div>

  );
}


export default Home;
