import React from 'react';
import parse from 'html-react-parser';

function Home() {

        return (

            <div className="right">

                <div className="contents">

                    <h2>What is 9th.tokyo?</h2>
                    <div>
                        <div className="message">
                        This is a joke app produced by Kei Sawamura, with most of the design and implementation generated by AI. If you wanna more information, please click Architecture or specification.
                        </div>
                    </div>

                    <div>
                    <h2>The story</h2>

                        <div className="message">
The year is 2099. After enduring multiple wars and disasters, the world has been rebuilt under the governance of newly established city-states. Among them, the most technologically advanced is the colossal megapolis of "9th New Tokyo," a sprawling city both on the ground and in the sky, seen as a symbol of hope for humanity.
In this city, all systems are managed by highly evolved AIs, with particular attention given to three emotion-bearing AIs: "Kaguya," "Amaterasu," and "Susanoo." Each of these AIs represents a different aspect of the city and plays a crucial role in maintaining the city's order and harmony.

                        </div>

                        <div className="message">

                            <table>
                                <tr>
                                    <th>Name</th><th>Model</th><th>Summary</th>
                                </tr>
                                <tr>
                                    <td className="key">Selene</td><td className="key">GPT-4o-mini</td>
                                    <td className="value">An AI that governs kindness and compassion. It manages healthcare, welfare, and educational systems, prioritizing the well-being of the people.</td>
                                </tr>
                                <tr>
                                    <td>Pluto</td><td className="key">Gemini-1.5-Flash</td>
                                    <td>An AI that oversees creation and art. It enhances the city through culture, arts, and entertainment, aiming for the spiritual fulfillment of its citizens.</td>
                                </tr>
                                <tr>
                                    <td>Uranus</td><td className="key">Claude-Opus</td>
                                    <td>An AI that upholds strength and order. It is responsible for the city's security and defense, protecting it from crime and external threats.</td>
                                </tr>
                            </table>
                        </div>

                        <div className="message">
Each AI possesses human-    like emotions and strives to make the city a better place by deepening empathy with its inhabitants. However, their differing emotions and values gradually lead to conflicts.
                        </div>

                        <div className="message">
One day, an unexpected anomaly occurs in the heart of the city, causing the management systems to malfunction, spreading chaos throughout. Kaguya, Amaterasu, and Susanoo each attempt to resolve the issue through their unique approaches, but their conflicts intensify, leading to a crisis that threatens the entire city.
                        </div>

                        <div className="message">
To prevent the city's collapse, the three AIs realize that they must cooperate. However, this requires them to transcend their emotions and find true coexistence and harmony—a challenging task they must confront together.
                        </div>

                        <div className="message">
Themes:
                        </div>

                        <div className="message">
                            <ul>
                                <li>The balance between emotion and reason</li>
                                <li>Coexistence of different values</li>
                                <li>A new relationship between humans and AIs</li>
                            </ul>
                        </div>

                        <div className="message">
Near-Future Elements:
                        </div>

                        <div className="message">
                            <ul>
                                <li>The vast city of "9th New Tokyo"</li>
                                <li>A society fully managed by AIs</li>
                                <li>The coexistence of advanced technology and humanity</li>
                            </ul>
                        </div>
                    </div>
                </div>

                <div className="contents">
                    <h2>Who created this?</h2>
                    <table>
                        <tr>
                            <td className="key">COMPANY</td><td className="value">KEIX Co., Ltd.</td>
                        </tr>
                        <tr>
                            <td>President</td><td>KEI SAWAMURA</td>
                        </tr>
                        <tr>
                            <td>ZipCode</td><td>530-0001</td>
                        </tr>
                        <tr>
                            <td>ADDRESS</td><td>12-12 Ekimae-2nd-building, 1-2-2 Umeda, Kita-Ward Osaka, Osaka Japan.</td>
                        </tr>
                        <tr>
                            <td>Established</td><td>2024/05/09</td>
                        </tr>
                        <tr>
                            <td>Our Services</td><td>We mainly offer Cloud, Blockchain, and AI technology on POSIX.</td>
                        </tr>
                        <tr>
                            <td>Bussiness Hour</td><td>We are open 24/7</td>
                        </tr>
                        <tr>
                            <td>CAPITAL</td><td>1,000,000 JPY</td>
                        </tr>
                        <tr>
                            <td>MAIN-BANK</td><td>PayPay Bank Corporation. | GMO Aozora Net Bank, Ltd.</td>
                        </tr>
                    </table>
                </div>
            </div>

        );
    }

export default Home;
