import React from 'react';
//import parse from 'html-react-parser';

function Home() {

        return (

            <div className="right main-contents">

                <div className="contents">

                    <h2>What is 9th.tokyo?</h2>
                    <div>
                        <div className="message">
                        This is a joke app produced by Kei Sawamura, with most of the design and implementation generated by AI. If you wanna more information, please click Architecture or specification.
                        </div>
                    </div>
                </div>

                <div className="contents">
                    <div>
                    <h2>The story</h2>

                        <div className="message">
The year is 2099. After enduring multiple wars and disasters, the world has been rebuilt under the governance of newly established city-states. Among them, the most technologically advanced is the colossal megapolis of "9th New Tokyo," a sprawling city both on the ground and in the sky, seen as a symbol of hope for humanity.
In this city, all systems are managed by highly evolved AIs, with particular attention given to three emotion-bearing AIs: "Kaguya," "Amaterasu," and "Susanoo." Each of these AIs represents a different aspect of the city and plays a crucial role in maintaining the city's order and harmony.
                        </div>

                        <div className="message">

                            <table>
                                <tr>
                                    <th>Name</th><th>Model</th><th>Summary</th>
                                </tr>
                                <tr>
                                    <td className="key">Selene</td><td className="key">GPT-4o-mini</td>
                                    <td className="value">An AI that governs kindness and compassion. It manages healthcare, welfare, and educational systems, prioritizing the well-being of the people.</td>
                                </tr>
                                <tr>
                                    <td>Artemis</td><td className="key">Gemini-1.5-Flash</td>
                                    <td>An AI that oversees creation and art. It enhances the city through culture, arts, and entertainment, aiming for the spiritual fulfillment of its citizens.</td>
                                </tr>
                                <tr>
                                    <td>Diana</td><td className="key">Claude-Opus</td>
                                    <td>An AI that upholds strength and order. It is responsible for the city's security and defense, protecting it from crime and external threats.</td>
                                </tr>
                            </table>

                        </div>

                        <div className="message">
Each AI possesses human-like emotions and strives to make the city a better place by deepening empathy with its inhabitants. However, their differing emotions and values gradually lead to conflicts.
                        </div>

                        <div className="message">
One day, an unexpected anomaly occurs in the heart of the city, causing the management systems to malfunction, spreading chaos throughout. Selene, Artemis, and Diana each attempt to resolve the issue through their unique approaches, but their conflicts intensify, leading to a crisis that threatens the entire city.
                        </div>

                        <div className="message">
To prevent the city's collapse, the three AIs realize that they must cooperate. However, this requires them to transcend their emotions and find true coexistence and harmony—a challenging task they must confront together.
                        </div>

                        <div className="message">
Themes:
                        </div>

                        <div className="message">
                            <ul>
                                <li>The balance between emotion and reason</li>
                                <li>Coexistence of different values</li>
                                <li>A new relationship between humans and AIs</li>
                            </ul>
                        </div>

                        <div className="message">
Near-Future Elements:
                        </div>

                        <div className="message">
                            <ul>
                                <li>The vast city of "9th New Tokyo"</li>
                                <li>A society fully managed by AIs</li>
                                <li>The coexistence of advanced technology and humanity</li>
                            </ul>
                        </div>
                    </div>
                </div>
                <div className="contents">
                    <div>
                        <div className="message">
                            <h2>The city view</h2>
                            <div className="left identify-colmun-left">
                                <p><img className="rounded" alt="city view" src="images/9th.tokyo.city.png" height="200" width="200" /></p>
                            </div>
                            <div className="right identify-colmun-right">
                                <h3> August 19, 2099 | 9th New Tokyo, Japan </h3>
                                <div className="message">
                                Today, amidst worldwide attention and great anticipation, the floating city "9th New Tokyo" has finally been completed and officially opened. This colossal megapolis, which spans both the ground and the sky, stands as a testament to human ingenuity and technological advancement, representing one of the most sophisticated and advanced cities ever built on Earth.
                                </div>

                                <div className="message">
The inception of "9th New Tokyo" was driven by the vision of creating a resilient and innovative society in response to the many wars and natural disasters that devastated the world in the latter half of the 21st century. The city is not only a marvel of engineering but also a symbol of humanity’s enduring spirit and its ability to rebuild and thrive after adversity. The city’s infrastructure includes floating buildings, aerial platforms, and interconnected networks that stretch high into the sky, designed to foster a new era of prosperity and peace.
                                </div>
                            </div>

                            <div className="message">
At the heart of this city’s operation is an advanced network of AI systems that manage everything from transportation and energy to public services and security. These AI systems are highly developed, ensuring the city runs smoothly, efficiently, and sustainably. "9th New Tokyo" is more than just a city; it is a beacon of hope, embodying the future of urban living and the promise of a better tomorrow for all humanity.
                            </div>
                        </div>
                    </div>
                </div>
                <div className="contents">
                    <div>

                        <div className="message">
                        <h2>Who created this?</h2>
                        <table>
                            <tr>
                                <td className="who-created-this">Executive Production</td><td>KEIX Co., Ltd.</td>
                            </tr>
                            <tr>
                                <td>Requirements Definition</td><td>Chat-GPT-4o / Claude-Opus</td>
                            </tr>
                            <tr>
                                <td>High-Level Design</td><td>Kei Sawamura / Chat-GPT-4o</td>
                            </tr>
                            <tr>
                                <td>Detailed Design</td><td>Chat-GPT-4o</td>
                            </tr>
                            <tr>
                                <td>Implementation</td><td>Kei Sawamura with Github Copilot / Chat-GPT-4o</td>
                            </tr>
                            <tr>
                                <td>Comprehensive Test Design</td><td>Chat-GPT-4o</td>
                            </tr>
                            <tr>
                                <td>Story Writing</td><td>Chat-GPT-4o / Claude-Opus</td>
                            </tr>
                            <tr>
                                <td>Post-Deployment Support</td><td>KEIX Co., Ltd.</td>
                            </tr>
                        </table>
                    </div>
                </div>
            </div>
        </div>

        );
    }

export default Home;
