import React from 'react';
import parse from 'html-react-parser';

function MainContents() {    
    return (

        <div className="right">

            <div className="contents">
                <h2>The Architecture of 9th.tokyo</h2>

                <div>
application is developed using TypeScript with React for the frontend (Current View), and Python's FastAPI framework served by Nginx with Uvicorn for the backend, It runs on a native Linux, not Dockerized. The article generation system relies on the Threads API and Gemini-1.5-Flash, and it runs on Lambda. Articles generated by AI are stored in Milvus. The source code is available for you to use, modify, and redistribute.
                </div>
                <br />

                <div>
 feature is developing in this branch, which is a similar search feature with the articles.
y's architecture diagram is as follows:
                </div>

            </div>

            <div className="contents">
                <img src="images/design-light.png" width="800" height="355" />
            </div>

            <div className="contents">
                <h2>
                    <a href="https://github.com/keix-luna/9th.tokyo">#9th.tokyo</a>
                </h2>
                <div className="text">
e API client for the Seven-Swords project renders JSON data in HTML, providing an intuitive interface for users. The name draws inspiration from the 3rd New Tokyo City in Evangelion, reflecting the project's focus on advanced technology.
                </div>
                <div className="text">
itially, it was a simple React-based client. Over time, the architecture expanded to include AWS Lambda functions, integrating with services like Milvus and Gemini. These additions enabled complex tasks like vector retrieval and similarity search.
                </div>
            </div>

            <div className="contents">
                <h2>
                    <a href="https://github.com/keix-luna/seven-swords">#Seven-Swords</a>
                </h2>
                <div className="text">
ven-Swords operates as a FastAPI application, reverse-proxied by NGINX for secure and efficient HTTP handling. The FastAPI backend queries Milvus for vectors, delivering fast and relevant results.
                </div>
                <div className="text">
e infrastructure is robust, with the FastAPI app running in a Docker container on an EC2 instance within a private subnet. External access is managed by an ALB, while internal resources use a NAT gateway for outbound connections.
                </div>
                <div className="text">
erall, Seven-Swords leverages Docker, FastAPI, Milvus, and AWS Lambda to provide a scalable and secure solution, capable of handling complex data processing tasks while allowing for future growth.
                </div>
            </div>

            <div className="contents">
                <h2>
                    <a href="https://github.com/keix-luna/akatsuki">#Akatsuki</a>
                </h2>
                <div>
                This is the source code for the infrastructure built using AWS CDK, which supports the 9th.tokyo and Seven-Swords projects. The name is Akatsuki a.k.a MoonLight. This project includes lambda functions to connect Gamini-1.5-Flash and Milvus.
                </div>
            </div>

        </div>

    );
}

export default MainContents;
