import React from 'react';
import parse from 'html-react-parser';
import design from './design.png';

interface Content { section: string; body: string; }
interface Props {content: Content[]}

class Photos extends React.Component<Props> {
    
    render() {
        return (

            <div className="right">

                <div className="contents">
                    <h2>The Architecture of 9th.tokyo</h2>

                    <div>
The application is developed using TypeScript with React for the frontend (Current View), and Python's FastAPI framework served by Nginx with Uvicorn for the backend, It runs on a native Linux, not Dockerized. The article generation system relies on the Threads API and Gemini-1.5-Flash, and it runs on Lambda. Articles generated by AI are stored in Milvus. The source code is available for you to use, modify, and redistribute.
                    </div>
                    <br />

                    <div>
Next feature is developing in this branch, which is a similar search feature with the articles.
Today's architecture diagram is as follows:
                    </div>

                </div>

                <div className="contents">
                    <img src={design} width="800" height="355" />
                </div>


                { this.props.content.map((content, index) => {
                    return (
                        <div className="contents" key={index}>
                            <h2>{content.section}</h2>
                            <div>{parse(content.body)}</div>
                        </div>
                        );
                    })
                }

                <div className="contents">
                    <h2>
                        <a href="https://github.com/keix-luna/9th.tokyo">#9th.tokyo</a>
                    </h2>
                    <div>
                    An API client for the Seven-Swords that renders JSON in HTML. The inspiration for the name of this application came from the 3rd New Tokyo City in Evangelion. It is just React!
                    </div>
                </div>

                <div className="contents">
                    <h2>
                        <a href="https://github.com/keix-luna/asteroid">#Asteroid</a>
                    </h2>
                    <div>
                    The central controller, which gathers data from cloud-based sources for the application, has an HTTP interface and always returns JSON. Inplemented Nginx and FastAPI.
                    </div>
                </div>

                <div className="contents">
                    <h2>
                        <a href="https://github.com/keix-luna/seven-swords">#Seven-Swords</a>
                    </h2>
                    <div>
                    The Lambda function includes a set of API wrappers named Asteroid that generate articles using various APIs. It is invoked when the client makes an HTTP request.
                    </div>
                </div>

            </div>

        );
    }
}

export default Photos;
